import { CreateProductDto } from "./dto/products.dto";
import {
  AgeGroup,
  EthicalPreferences,
  HairType,
  Ingredients,
  ProductPurpose,
  SkinConcern,
  SkinType,
  UsageTime,
} from "./products.model";

export const productsData: CreateProductDto[] = [
  {
    categoryId: "1649e86b-4660-4e97-9bf2-4e41c4ade850",
    productName: "Интенсивный увлажняющий крем для лица",
    description:
      "Глубоко увлажняет и восстанавливает кожу, предотвращает появление морщин.",
    imageURL: "https://m.media-amazon.com/images/I/61pIL2maVKL.jpg",
    skinType: SkinType.Dry,
    ageGroup: AgeGroup.Young,
    skinConcern: [SkinConcern.Dryness],
    usageTime: UsageTime.Morning,
    ingredients: [Ingredients.HyaluronicAcid, Ingredients.VitaminC],
    ethicalPreferences: [
      EthicalPreferences.CrueltyFree,
      EthicalPreferences.Organic,
    ],
    purpose: [ProductPurpose.Hydration],
    brand: "HydraGenius",
  },
  {
    categoryId: "032e07b5-9136-47a0-b1e4-0e6bb5ee88a7",
    productName: "Восстанавливающий шампунь для волос",
    description:
      "Укрепляет корни волос и способствует их росту, предотвращает выпадение волос.",
    imageURL: "https://assets.unileversolutions.com/v1/41760797.png",
    hairType: HairType.Dry,
    ageGroup: AgeGroup.Mature,
    usageTime: UsageTime.Evening,
    ingredients: [Ingredients.Peptides, Ingredients.VitaminB3],
    ethicalPreferences: [EthicalPreferences.EcoPackaging],
    purpose: [ProductPurpose.Nutrition],
    brand: "StrengthHair",
  },
  {
    categoryId: "83df2410-81e8-4855-8965-48a5e2a35bcc",
    productName: "Солнцезащитный крем SPF 50",
    description:
      "Обеспечивает высокую защиту от UVA и UVB лучей, подходит для чувствительной кожи.",
    imageURL:
      "https://media-pierre-fabre.wedia-group.com/api/wedia/dam/transform/u5wa3z31qn5sjgcy944kwcy615y96p4oxfa67sa/pf_square/u5wa3z31qn5sjgcy944kwcy615y96p4oxfa67sa?t=resize&height=700",
    skinType: SkinType.Normal,
    ageGroup: AgeGroup.Senior,
    skinConcern: [SkinConcern.Sensitivity],
    usageTime: UsageTime.Morning,
    ingredients: [Ingredients.SPF],
    ethicalPreferences: [
      EthicalPreferences.NoChemicals,
      EthicalPreferences.CrueltyFree,
    ],
    purpose: [ProductPurpose.Protection],
    brand: "SunBlocker",
  },
  {
    categoryId: "769761ad-9d4a-400d-9492-2aed9a8e4659",
    productName: "Антивозрастная сыворотка для лица",
    description:
      "Сокращает видимость морщин и восстанавливает упругость кожи, стимулируя производство коллагена.",
    imageURL:
      "https://www.laroche-posay.ru/media/catalog/product/cache/a7cd5d8a509e2b0bafdb22dbf111cc56/g/r/group_35.jpg",
    skinType: SkinType.Normal,
    ageGroup: AgeGroup.Mature,
    skinConcern: [SkinConcern.WrinklesAndLines, SkinConcern.Pigmentation],
    usageTime: UsageTime.Evening,
    ingredients: [
      Ingredients.Retinol,
      Ingredients.Peptides,
      Ingredients.VitaminC,
    ],
    ethicalPreferences: [
      EthicalPreferences.CrueltyFree,
      EthicalPreferences.NoChemicals,
    ],
    purpose: [ProductPurpose.Nutrition, ProductPurpose.Protection],
    brand: "AgeDefy",
  },
  {
    categoryId: "98a70aba-88b1-4b1b-8b4a-054ae2dbf501",
    productName: "Очищающий гель для умывания",
    description: "Глубоко очищает поры и удаляет макияж, не пересушивая кожу.",
    imageURL: "https://ir.ozone.ru/s3/multimedia-3/c1000/6675695103.jpg",
    skinType: SkinType.Oily,
    ageGroup: AgeGroup.Young,
    skinConcern: [SkinConcern.AcneAndBreakouts],
    usageTime: UsageTime.Morning,
    ingredients: [Ingredients.AloeVera, Ingredients.VitaminB3],
    ethicalPreferences: [EthicalPreferences.EcoPackaging],
    purpose: [ProductPurpose.Cleansing],
    brand: "PureSkin",
  },
  {
    categoryId: "98a70aba-88b1-4b1b-8b4a-054ae2dbf501",
    productName: "Крем для умывания",
    description: "Увлажняет кожу и очищает ее.",
    imageURL:
      "https://french-house.kz/upload/ammina.optimizer/jpg-webp/q80/upload/iblock/d40/8lp2f3c39br45kvqt5tj1sxzxgvnbxu9.webp",
    skinType: SkinType.Oily,
    ageGroup: AgeGroup.Young,
    skinConcern: [SkinConcern.AcneAndBreakouts],
    usageTime: UsageTime.Morning,
    ingredients: [Ingredients.AloeVera, Ingredients.VitaminB3],
    ethicalPreferences: [EthicalPreferences.EcoPackaging],
    purpose: [ProductPurpose.Cleansing],
    brand: "PureSkin",
  },
  {
    categoryId: "98a70aba-88b1-4b1b-8b4a-054ae2dbf501",
    productName: "Пенка для умывания Nextbeauty",
    description: "Глубокое очищение кожи лица, для жирной кожи",
    imageURL: "https://images.satu.kz/184541550_w600_h600_184541550.jpg",
    skinType: SkinType.Oily,
    ageGroup: AgeGroup.Young,
    skinConcern: [SkinConcern.AcneAndBreakouts],
    usageTime: UsageTime.Morning,
    ingredients: [Ingredients.AloeVera, Ingredients.VitaminB3],
    ethicalPreferences: [EthicalPreferences.EcoPackaging],
    purpose: [ProductPurpose.Cleansing],
    brand: "PureSkin",
  },
  {
    categoryId: "98a70aba-88b1-4b1b-8b4a-054ae2dbf501",
    productName: "Крем для умывания Libre Derm",
    description: "Глубоко очищает поры и удаляет макияж, увлажняет кожу.",
    imageURL: "https://cdn1.ozone.ru/s3/multimedia-y/6370215538.jpg",
    skinType: SkinType.Oily,
    ageGroup: AgeGroup.Young,
    skinConcern: [SkinConcern.AcneAndBreakouts],
    usageTime: UsageTime.Morning,
    ingredients: [Ingredients.AloeVera, Ingredients.VitaminB3],
    ethicalPreferences: [EthicalPreferences.EcoPackaging],
    purpose: [ProductPurpose.Cleansing],
    brand: "PureSkin",
  },
  {
    categoryId: "98a70aba-88b1-4b1b-8b4a-054ae2dbf501",
    productName: "Atomi centella гель для умывания",
    description: "Глубоко очищает поры и очищает, увлажняет кожу.",
    imageURL: "https://static-global-shopping.atomy.com/kz/F00779/thumb1.jpg",
    skinType: SkinType.Oily,
    ageGroup: AgeGroup.Young,
    skinConcern: [SkinConcern.AcneAndBreakouts],
    usageTime: UsageTime.Morning,
    ingredients: [Ingredients.AloeVera, Ingredients.VitaminB3],
    ethicalPreferences: [EthicalPreferences.EcoPackaging],
    purpose: [ProductPurpose.Cleansing],
    brand: "PureSkin",
  },
  {
    categoryId: "769761ad-9d4a-400d-9492-2aed9a8e4659",
    productName: "Питательный крем для тела",
    description:
      "Интенсивно увлажняет и питает кожу тела, оставляя её мягкой и гладкой на весь день.",
    imageURL:
      "https://ecoboom.kz/wp-content/uploads/2022/02/Krem-dlya-tela-Pitatelnyj.jpg",
    skinType: SkinType.Dry,
    ageGroup: AgeGroup.PreSenior,
    skinConcern: [SkinConcern.Dryness, SkinConcern.Dehydration],
    usageTime: UsageTime.Evening,
    ingredients: [Ingredients.HyaluronicAcid, Ingredients.Zinc],
    ethicalPreferences: [
      EthicalPreferences.Organic,
      EthicalPreferences.CrueltyFree,
    ],
    purpose: [ProductPurpose.Hydration, ProductPurpose.Nutrition],
    brand: "BodyLux",
  },
  {
    categoryId: "98a70aba-88b1-4b1b-8b4a-054ae2dbf501",
    productName: "Эксфолирующий скраб для лица",
    description:
      "Мягко удаляет омертвевшие клетки кожи, способствуя обновлению и улучшению текстуры кожи.",
    imageURL:
      "https://articoli.ru/upload/iblock/7e1/7e1d3bdb054023f5edde7f908fd4d755.jpg",
    skinType: SkinType.Normal,
    ageGroup: AgeGroup.Young,
    skinConcern: [SkinConcern.Dryness],
    usageTime: UsageTime.Evening,
    ingredients: [Ingredients.VitaminC, Ingredients.AloeVera],
    ethicalPreferences: [
      EthicalPreferences.EcoPackaging,
      EthicalPreferences.NoChemicals,
    ],
    purpose: [ProductPurpose.Cleansing],
    brand: "SmoothGlow",
  },
];
